# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.112.0"

default_platform :ios

platform :ios do
  lane :build_production_library do
    Dir.chdir("../src/tools_webrtc/ios") do
      sh("python", "build_ios_libs.py")
      sh("cp", "-fr", "../../out_ios_libs/WebRTC.framework", "../../../output/release/")
    end
  end

  lane :build_bitcode_library do
    Dir.chdir("../src/tools_webrtc/ios") do
      sh("python", "build_ios_libs.py", "--bitcode")
      sh("cp", "-fr", "../../out_ios_libs/WebRTC.framework", "../../../output/bitcode/")
    end
  end

  lane :release do
    build_production_library
    build_bitcode_library
  end
end
