# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "694ded81-fb40-4a37-82a8-aa2a99be14c7"

default_platform :ios

platform :ios do
  lane :build_development_library do
    Dir.chdir("../src/tools_webrtc/ios") do
      sh("python", "build_ios_libs.py", "--bitcode")
    end
  end

  lane :build_production_library do
    Dir.chdir("../src/tools_webrtc/ios") do
      sh("python", "build_ios_libs.py", "--bitcode", "--arch", "arm64")
    end
end

end
